@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@contentType = application/json

@tripId = {{createTrip.response.body.tripId}}
@participantId = 740ef913-1994-4855-84f9-b641082b7cd0

# @name createTrip
POST http://{{host}}/trips
Content-Type: {{contentType}}

{
  "destination": "Toronto",
  "startsAt": "2025-01-01",
  "endsAt": "2026-01-01",
  "ownerName": "Guilherme Crozariol",
  "ownerEmail": "guicrozariol@gmail.com",
  "emailsToInvite": [
    "john.doe@example.com",
    "jane.smith@example.net",
    "sam.wilson@example.org",
    "linda.brown@example.edu",
    "michael.jones@example.co",
    "emily.davis@example.io",
    "chris.miller@example.biz",
    "patricia.garcia@example.info",
    "daniel.moore@example.tech",
    "sarah.lee@example.dev"
  ]
}

###

# @name confirmTrip
GET http://{{host}}/trips/{{tripId}}/confirm
Content-Type: {{contentType}}

###

# @name confirmParticipant
GET http://{{host}}/participants/{{participantId}}/confirm
Content-Type: {{contentType}}

###

# @name createActivity
POST http://{{host}}/trips/41f5bd30-5eab-4e35-ab85-8996893eb1e1/activities
Content-Type: {{contentType}}

{
  "title": "im here"
}