@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name createTrip
POST http://{{host}}/trips
Content-Type: {{contentType}}

{
  "destination": "Toronto",
  "startsAt": "2025-01-01",
  "endsAt": "2026-01-01",
  "ownerName": "Guilherme Crozariol",
  "ownerEmail": "guicrozariol@gmail.com",
  "emailsToInvite": [
    "john.doe@example.com",
    "jane.smith@example.net",
    "sam.wilson@example.org",
    "linda.brown@example.edu",
    "michael.jones@example.co",
    "emily.davis@example.io",
    "chris.miller@example.biz",
    "patricia.garcia@example.info",
    "daniel.moore@example.tech",
    "sarah.lee@example.dev"
  ]
}

###

# @name confirmTrip
GET http://{{host}}/trips/a6639f6e-a685-40c2-afa5-6b200fd82a1d/confirm

###

# @name confirmParticipant
GET http://{{host}}/participants/bbda33d3-3b12-423a-900a-86b710700eb0/confirm